### ISSUE TITLE
[bug] 1.8.0 breaks support for legacy config

### ISSUE THREAD

**Issue by alex-kinokon** [Rel1cx/eslint-react#686]
### Describe the bug

```
Error: Failed to load config "plugin:@eslint-react/recommended-legacy" to extend from.
```

Broken between 1.8.0-beta.1 and 1.8.0-next.2. [Git compare link](https://github.com/Rel1cx/eslint-react/compare/7290bde9126f7a78c2dd347cc4e8d5fde09a1f9b...2fa81fe08808a4d45b15ec8efa7efa3d299c0a2b).

ESLint’s `_loadPlugin(pluginName, ctx)` got a plugin where `configs` other properties are all empty objects.

### Reproduction

https://github.com/alex-kinokon/esr-bug-r

### Platform and versions

```Text
Node v22.5.1
```

### Stack trace

```Text
at configInvalidError (/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
    at ConfigArrayFactory._loadExtendedPluginConfig (/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3246:31)
    at ConfigArrayFactory._loadExtends (/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
```

**Comment by Rel1cx** [comment]
This may be caused by using both `export` and `export default` in the `@eslint-react/eslint-plugin` package. Please try upgrading to `1.8.2-next.0` to see if it is solved.
